config/routes.rb
Rails.application.routes.draw do
  root to: "home#show"

  resources :mailers, only: [:create]

  get "/sent", to: "mailers#sent"

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/controllers/mailers_controller.rb
class MailersController < ApplicationController
  def create
    UserNotifierJob.perform_later(params[:mailers][:email], params[:mailers][:thought])
    # UserNotifier.send_randomness_email(params[:mailers][:email], params[:mailers][:thought]).deliver_now
    flash[:message] = "You did it! Email sent to #{params[:mailers][:email]}"
    redirect_to "/sent"
  end

  def sent
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mailers_helper.rb
module MailersHelper
end

app/views/home/show.html.erb
<div class="container box">
  <div class="center">

    <h1>Welcome to Working-It</h1>

  </div>

  <h1 class="form">
  <%= form_for :mailers, url: mailers_path do |f| %>
  <%= f.label "Email -" %>
  <%= f.text_field :email %><br>
  <%= f.label "Thought?" %>
  <%= f.text_field :thought %><br>
  <%= f.submit "Give me the randomness...", class: "center" %>
  <% end %>
  </h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WorkIt</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%  flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
  <% end %>
<%= yield %>

</body>
</html>

app/views/user_notifier/send_randomness_email.html.erb
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <h1>Thanks for requesting a randomness email!</h1>
    <p>Thanks for joining and have a great day! Now sign in and do
awesome things!</p>
    Your thoughts are like:
    <%= image_tag @thought_image %>
  </body>
</html>